### PR TITLE
added copy address icon & functionality on displayAddress

### PR DESCRIPTION
**Pull request by gabrieltemtsen**
poidh_demo

### CODE REVIEW

**Review by yukigesho — COMMENTED** [review]
In this way, we impact all addresses. I suggest moving the copy as a separate component and reusing it

**Comment by gabrieltemtsen** [comment]
> In this way, we impact all addresses. I suggest moving the copy as a separate component and reusing it

Alright!

**Comment by gabrieltemtsen** [comment]
> In this way, we impact all addresses. I suggest moving the copy as a separate component and reusing it

@yukigesho  how do you see these below   
image
image

**Comment by gabrieltemtsen** [comment]
> In this way, we impact all addresses. I suggest moving the copy as a separate component and reusing it

@yukigesho  here I just added an optional prop to displayAddress to either show the copyAddressIcon or not, so we could get a better look
image

image

**Pull request closed without merging**
